# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_types', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_zoom', models.FloatField(blank=True, null=True)),
                ('filterQuery', models.CharField(blank=True, max_length=255, null=True)),
                ('filterIsValid', models.BooleanField(default=True)),
                ('filter', models.CharField(blank=True, max_length=400, null=True)),
                ('isFavourite', models.BooleanField(default=False)),
                ('chart_title', models.CharField(blank=True, max_length=100, null=True)),
                ('filter_rules', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis_types.AnalysisType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
