# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0003_selectedvariables'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedvariables',
            name='variable_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
