# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected_databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connecteddatabase',
            name='database_type',
            field=models.CharField(choices=[('PostgreSQL', 'postgresql+psycopg2'), ('MySQL', 'mysql+pymysql'), ('MSSQL', 'mssql')], default='PostgreSQL', max_length=255, null=True),
        ),
    ]
