# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected_databases', '0002_auto_20180924_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connecteddatabase',
            name='database_type',
            field=models.CharField(choices=[('postgresql+psycopg2', 'PostgreSQL'), ('mysql+pymysql', 'MySQL'), ('mssql', 'MSSQL')], default='postgresql+psycopg2', max_length=255, null=True),
        ),
    ]
