# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0004_selectedvariables_variable_id'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='workboards',
            field=models.ManyToManyField(to='workboard.Workboard'),
        ),
    ]
