# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=profiles.models.upload_location),
        ),
    ]
