# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('button_class', models.CharField(max_length=255)),
                ('icon_class', models.CharField(max_length=255)),
                ('selected', models.BooleanField(default=False)),
                ('analytics', models.CharField(max_length=500)),
                ('customClass', models.CharField(max_length=255)),
            ],
        ),
    ]
